In [1]:
import numpy as np

arr = np.array([[3, 6, 2, 4]], np.int64)
arr[0, 1]

np.int64(6)

In [2]:
arr.shape

(1, 4)

In [3]:
arr[0,1] = 45
arr

array([[ 3, 45,  2,  4]])

# Array Creation: Conversion from other Python Structures

In [4]:
listarr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
listarr.dtype

dtype('int64')

In [7]:
listarr.shape

(3, 3)

In [8]:
listarr.size

9

In [9]:
np.array({34, 23, 67})

array({34, 67, 23}, dtype=object)

In [10]:
zeros_arr = np.zeros((2,5))

In [11]:
zeros_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
zeros_arr.shape

(2, 5)

In [13]:
zeros_arr.dtype

dtype('float64')

In [14]:
zeros_arr.size

10

In [15]:
range_arr = np.arange(15)

In [16]:
range_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
len(range_arr)

15

In [18]:
lspace_arr = np.linspace(1, 5, 10)

In [19]:
lspace_arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
emp_arr = np.empty((4, 6))

In [21]:
emp_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.33644129e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37959740e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
       [6.23059726e-307, 1.42419530e-306, 1.11261027e-306,
        1.95819401e-306, 1.11261502e-306, 1.42410974e-306]])

In [24]:
emp_like_arr = np.empty_like(lspace_arr)

In [25]:
emp_like_arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [26]:
idn_arr = np.identity(10)

In [27]:
idn_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
arr2 = np.arange(99)

In [29]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr2 = arr2.reshape(3, 33)

In [38]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr2 = arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
ar = np.array(x)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.sum(axis=0)

array([12, 15, 18])

In [45]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
ar.flat

In [49]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [50]:
ar.ndim

2

In [51]:
ar.size

9

In [52]:
ar.nbytes

72

In [53]:
one = np.array([1, 3, 4, 634, 2])

In [55]:
one.argmax()

np.int64(3)

In [56]:
one.argmin()

np.int64(0)

In [57]:
one.argsort()

array([0, 4, 1, 2, 3])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
ar.argmin()

np.int64(0)

In [60]:
ar.argmax()

np.int64(8)

In [62]:
ar.argmax(axis=0)

array([2, 2, 2])

In [63]:
ar.argmax(axis=1)

array([2, 2, 2])

In [61]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [66]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [75]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [77]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
ar2 = np.array([[8, 6, 7],
       [2, 4, 3],
       [1, 9, 5]])

In [79]:
ar2

array([[8, 6, 7],
       [2, 4, 3],
       [1, 9, 5]])

In [80]:
ar + ar2

array([[ 9,  8, 10],
       [ 6,  9,  9],
       [ 8, 17, 14]])

In [81]:
ar * ar2

array([[ 8, 12, 21],
       [ 8, 20, 18],
       [ 7, 72, 45]])

In [82]:
np.sqrt(ar2)

array([[2.82842712, 2.44948974, 2.64575131],
       [1.41421356, 2.        , 1.73205081],
       [1.        , 3.        , 2.23606798]])

In [86]:
ar2

array([[8, 6, 7],
       [2, 4, 3],
       [1, 9, 5]])

In [83]:
ar2.sum()

np.int64(45)

In [84]:
ar2.min()

np.int64(1)

In [85]:
ar2.max()

np.int64(9)

In [89]:
np.where(ar2 > 6)

(array([0, 0, 2]), array([0, 2, 1]))

In [97]:
ar3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])

In [98]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [99]:
np.count_nonzero(ar3)

8

In [101]:
np.nonzero(ar3)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [105]:
import sys

In [106]:
py_arr = [0, 4, 55, 2]

In [107]:
np_arr = np.array(py_arr)

In [108]:
sys.getsizeof(1) * len(py_arr)

112

In [109]:
np_arr.itemsize * np_arr.size

32